services:
  postgres:
    image: postgres:15.3  # Puedes cambiar a la versi칩n que prefieras
    environment:
      POSTGRES_USER: ${DB_USER}             # Nombre de usuario
      POSTGRES_PASSWORD: ${DB_PASSWORD}     # Contrase침a del usuario
      POSTGRES_DB: ${DB_NAME}               # Base de datos por defecto (opcional)
    ports:
      - "${DB_PORT}:5432"  # Puerto est치ndar de PostgreSQL
    volumes:
      - pg-data:/var/lib/postgresql/data  # Volumen para persistencia de datos
      - ./initdb:/docker-entrypoint-initdb.d  # Montar la carpeta de scripts de inicializaci칩n
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - app-network
volumes:
  pg-data:
  redis_data:

networks:
  app-network:
